package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

// buildMarkdown accumulates all categories into a single markdown document
// using pandoc fenced divs. Each page's worth of cards gets its own grid
// container div so CSS grid fragmentation is never needed — the renderer
// places each div on a fresh page via the ".category + .category" rule.
func buildMarkdown(categories []Category, version string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- Generated by cardsgen %s -->\n\n", version)
	for _, cat := range categories {
		if len(cat.Items) == 0 {
			continue
		}
		perPage := cat.Grid.Cols * cat.Grid.Rows
		for i := 0; i < len(cat.Items); i += perPage {
			end := i + perPage
			if end > len(cat.Items) {
				end = len(cat.Items)
			}
			fmt.Fprintf(&b, ":::::: {.category .category--%s}\n\n", cssName(cat.Name))
			for _, item := range cat.Items[i:end] {
				writeCard(&b, cat, item)
			}
			b.WriteString("::::::\n\n")
		}
	}
	return b.String()
}

// writeCard emits a single card div: a colored category bar, an optional
// background watermark, and the item body.
func writeCard(b *strings.Builder, cat Category, item Item) {
	fmt.Fprintf(b, "::::: {.card .card--%s}\n\n", cssName(cat.Name))

	fmt.Fprintf(b, ":::: {.card-bar}\n%s\n::::\n\n", barLabel(cat, item))

	b.WriteString(":::: {.card-body}\n\n")

	// print background inside body so it is clipped to the card's content box, not the full page
	if item.ImagePath != "" {
		fmt.Fprintf(b, ":::: {.card-watermark style=\"background-image: url('%s')\"}\n::::\n\n", fileURL(item.ImagePath))
	}

	fmt.Fprintf(b, "# %s\n\n", item.Title)
	if body := strings.TrimSpace(item.BodyMarkdown); body != "" {
		b.WriteString(body)
		b.WriteString("\n\n")
	}
	b.WriteString("::::\n\n") // .card-body

	b.WriteString(":::::\n\n") // .card
}

// barLabel is the text shown in the card's colored top bar.
func barLabel(cat Category, item Item) string {
	label := strings.ToUpper(cat.Name)
	if item.Subcategory != "" {
		label += " · " + item.Subcategory
	}
	return label
}

// cssName normalises a category name into a value safe for a CSS class suffix.
func cssName(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	return b.String()
}

// fileURL converts a local filesystem path into a file:// URL that weasyprint
// can resolve on any platform.
func fileURL(p string) string {
	abs, err := filepath.Abs(p)
	if err != nil {
		abs = p
	}
	s := filepath.ToSlash(abs)
	if !strings.HasPrefix(s, "/") {
		s = "/" + s // Windows drive paths like C:/...
	}
	return "file://" + s
}
